# Generated by Django 5.2.4 on 2026-04-20 07:00

from django.db import migrations


def create_default_organization_and_rbac(apps, schema_editor):
    """
    Create default organization, permissions, admin role,
    and assign all existing users to default organization with admin role.
    """
    Organization = apps.get_model('core', 'Organization')
    Permission = apps.get_model('core', 'Permission')
    Role = apps.get_model('core', 'Role')
    RolePermission = apps.get_model('core', 'RolePermission')
    User = apps.get_model('core', 'User')
    UserProfile = apps.get_model('userprofile', 'UserProfile')
    UserActivation = apps.get_model('core', 'UserActivation')
    ForgetPassword = apps.get_model('core', 'ForgetPassword')
    CompanyInfo = apps.get_model('core', 'CompanyInfo')
    
    # Create default organization
    default_org, _ = Organization.objects.get_or_create(
        name='Default Organization',
        defaults={
            'description': 'Default organization for existing users',
            'is_active': True
        }
    )
    
    # Create default permissions
    default_permissions = [
        # User permissions
        {'name': 'Create User', 'permission_code': 'user.create', 'description': 'Can create new users'},
        {'name': 'Read User', 'permission_code': 'user.read', 'description': 'Can view users'},
        {'name': 'Update User', 'permission_code': 'user.update', 'description': 'Can update users'},
        {'name': 'Delete User', 'permission_code': 'user.delete', 'description': 'Can delete users'},
        
        # Role permissions
        {'name': 'Create Role', 'permission_code': 'role.create', 'description': 'Can create roles'},
        {'name': 'Read Role', 'permission_code': 'role.read', 'description': 'Can view roles'},
        {'name': 'Update Role', 'permission_code': 'role.update', 'description': 'Can update roles'},
        {'name': 'Delete Role', 'permission_code': 'role.delete', 'description': 'Can delete roles'},
        
        # Organization permissions
        {'name': 'Create Organization', 'permission_code': 'organization.create', 'description': 'Can create organizations'},
        {'name': 'Read Organization', 'permission_code': 'organization.read', 'description': 'Can view organizations'},
        {'name': 'Update Organization', 'permission_code': 'organization.update', 'description': 'Can update organizations'},
        {'name': 'Delete Organization', 'permission_code': 'organization.delete', 'description': 'Can delete organizations'},
        
        # Profile permissions
        {'name': 'Create Profile', 'permission_code': 'profile.create', 'description': 'Can create profiles'},
        {'name': 'Read Profile', 'permission_code': 'profile.read', 'description': 'Can view profiles'},
        {'name': 'Update Profile', 'permission_code': 'profile.update', 'description': 'Can update profiles'},
        {'name': 'Delete Profile', 'permission_code': 'profile.delete', 'description': 'Can delete profiles'},
    ]
    
    permissions = []
    for perm_data in default_permissions:
        perm, _ = Permission.objects.get_or_create(
            permission_code=perm_data['permission_code'],
            defaults={
                'name': perm_data['name'],
                'description': perm_data['description']
            }
        )
        permissions.append(perm)
    
    # Create Admin role for default organization
    admin_role, _ = Role.objects.get_or_create(
        name='Admin',
        organization=default_org,
        defaults={
            'description': 'Administrator with full permissions',
            'is_active': True
        }
    )
    
    # Assign all permissions to Admin role
    for permission in permissions:
        RolePermission.objects.get_or_create(
            role=admin_role,
            permission=permission
        )
    
    # Assign all existing users to default organization with admin role
    for user in User.objects.filter(organization__isnull=True):
        user.organization = default_org
        user.role = admin_role
        user.save(update_fields=['organization', 'role'])
    
    # Update related models with organization
    for profile in UserProfile.objects.filter(organization__isnull=True):
        if profile.user and profile.user.organization:
            profile.organization = profile.user.organization
            profile.save(update_fields=['organization'])
    
    for activation in UserActivation.objects.filter(organization__isnull=True):
        if activation.user and activation.user.organization:
            activation.organization = activation.user.organization
            activation.save(update_fields=['organization'])
    
    for forget_pwd in ForgetPassword.objects.filter(organization__isnull=True):
        if forget_pwd.user and forget_pwd.user.organization:
            forget_pwd.organization = forget_pwd.user.organization
            forget_pwd.save(update_fields=['organization'])
    
    for company in CompanyInfo.objects.filter(organization__isnull=True):
        company.organization = default_org
        company.save(update_fields=['organization'])


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by removing organization references.
    """
    User = apps.get_model('core', 'User')
    
    # Set organization and role to null for all users
    User.objects.all().update(organization=None, role=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_permission_user_is_super_admin_and_more'),
        ('userprofile', '0002_userprofile_organization'),
    ]

    operations = [
        migrations.RunPython(create_default_organization_and_rbac, reverse_migration),
    ]
