# Generated by Django 5.2.4 on 2026-04-28 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_role_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN_PERMISSION', 'Assign Permission'), ('REMOVE_PERMISSION', 'Remove Permission')], help_text='Type of action performed', max_length=50)),
                ('model_name', models.CharField(help_text='Name of the model affected (e.g., User, Role, Organization)', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the affected object', max_length=255, null=True)),
                ('changes', models.JSONField(default=dict, help_text='JSON object storing before/after changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', null=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx'), models.Index(fields=['model_name', 'created_at'], name='core_auditl_model_n_0bad5d_idx'), models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx')],
            },
        ),
    ]
