# Generated by Django 5.2.4 on 2026-05-18 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Brand name (e.g., 'Samsung', 'Apple', 'Nike')", max_length=100)),
                ('code', models.CharField(help_text="Unique brand code for identification (e.g., 'SAMS', 'APPL')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the brand', null=True)),
                ('country', models.CharField(blank=True, help_text="Country of origin (e.g., 'South Korea', 'United States')", max_length=100, null=True)),
                ('website', models.URLField(blank=True, help_text='Brand website URL', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this brand is active and available for use')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Category name (e.g., 'Electronics', 'Furniture')", max_length=100)),
                ('code', models.CharField(help_text="Unique category code for identification (e.g., 'ELEC', 'FURN')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the category', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and available for use')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('code', models.CharField(help_text="Unique product code/SKU (e.g., 'PRD-001')", max_length=50)),
                ('barcode', models.CharField(blank=True, help_text='Product barcode (EAN, UPC, etc.)', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed product description', null=True)),
                ('product_type', models.CharField(choices=[('GOODS', 'Goods'), ('SERVICE', 'Service'), ('CONSUMABLE', 'Consumable')], default='GOODS', help_text='Type of product (affects inventory tracking)', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price per unit (purchase price)', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price per unit', max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0.0, help_text='Stock level at which to reorder', max_digits=12)),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity to order when restocking', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is active')),
                ('can_be_sold', models.BooleanField(default=True, help_text='Whether this product can be sold')),
                ('can_be_purchased', models.BooleanField(default=True, help_text='Whether this product can be purchased')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Product brand/manufacturer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.brand')),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_number', models.CharField(help_text='Unique adjustment reference number', max_length=50)),
                ('adjustment_date', models.DateField(help_text='Date of the adjustment')),
                ('reason', models.CharField(choices=[('DAMAGE', 'Damage'), ('LOSS', 'Loss/Theft'), ('FOUND', 'Found Items'), ('CORRECTION', 'Inventory Correction'), ('EXPIRY', 'Expiry'), ('QUALITY', 'Quality Issues'), ('OTHER', 'Other')], help_text='Reason for the adjustment', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Current status of the adjustment', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the adjustment', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Date and time when adjustment was approved', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_change', models.DecimalField(decimal_places=2, help_text='Quantity change (positive = add, negative = remove)', max_digits=12)),
                ('current_quantity', models.DecimalField(decimal_places=2, help_text='Current quantity before adjustment', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Notes about this item adjustment', null=True)),
                ('adjustment', models.ForeignKey(help_text='Parent adjustment record', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockadjustment')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('product', models.ForeignKey(help_text='Product being adjusted', on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_items', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Adjustment Item',
                'verbose_name_plural': 'Stock Adjustment Items',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_number', models.CharField(help_text='Unique transfer reference number', max_length=50)),
                ('transfer_date', models.DateField(help_text='Date of the transfer')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the transfer', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transfer', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when transfer was completed', null=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='User who completed the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_transfers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity to transfer', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Notes about this item', null=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('product', models.ForeignKey(help_text='Product being transferred', on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='inventory.product')),
                ('transfer', models.ForeignKey(help_text='Parent transfer record', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer')),
            ],
            options={
                'verbose_name': 'Stock Transfer Item',
                'verbose_name_plural': 'Stock Transfer Items',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Full unit name (e.g., 'Kilogram', 'Piece', 'Liter')", max_length=100)),
                ('code', models.CharField(help_text="Unique unit code for identification (e.g., 'KG', 'PCS', 'LTR')", max_length=50)),
                ('symbol', models.CharField(blank=True, help_text="Unit symbol for display (e.g., 'kg', 'pcs', 'L')", max_length=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the unit', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this unit is active and available for use')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(help_text='Unit of measurement', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unit'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Warehouse name (e.g., 'Main Warehouse', 'Store #1')", max_length=100)),
                ('code', models.CharField(help_text="Unique warehouse code for identification (e.g., 'WH-MAIN', 'STR-01')", max_length=50)),
                ('address', models.TextField(blank=True, help_text='Full street address of the warehouse', null=True)),
                ('city', models.CharField(blank=True, help_text='City where warehouse is located', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province where warehouse is located', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text='Country where warehouse is located', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code of the warehouse', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this warehouse is active and available for use')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_warehouse',
            field=models.ForeignKey(help_text='Warehouse stock is transferred to', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='source_warehouse',
            field=models.ForeignKey(help_text='Warehouse stock is transferred from', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT_ADD', 'Adjustment - Add'), ('ADJUSTMENT_REMOVE', 'Adjustment - Remove'), ('RETURN', 'Return'), ('DAMAGE', 'Damage/Loss'), ('OPENING', 'Opening Balance')], help_text='Type of stock movement', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity moved (positive or negative)', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Stock balance after this movement', max_digits=12)),
                ('reference_type', models.CharField(blank=True, help_text="Type of reference document (e.g., 'StockTransfer', 'PurchaseOrder')", max_length=50, null=True)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of the reference document', null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Reference document number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the movement', null=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of the movement')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('product', models.ForeignKey(help_text='Product that moved', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
                ('warehouse', models.ForeignKey(help_text='Warehouse where movement occurred', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse where adjustment occurs', on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Current quantity in stock', max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity reserved for pending orders', max_digits=12)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('product', models.ForeignKey(help_text='Product being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.product')),
                ('warehouse', models.ForeignKey(help_text='Warehouse location', on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Product Stock',
                'verbose_name_plural': 'Product Stocks',
            },
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['organization', 'code'], name='inventory_b_organiz_3c6e81_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['organization', 'is_active'], name='inventory_b_organiz_22d804_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organization', 'code'], name='inventory_c_organiz_b282b1_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organization', 'is_active'], name='inventory_c_organiz_157598_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organization', 'parent'], name='inventory_c_organiz_ae0e84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='stockadjustmentitem',
            index=models.Index(fields=['organization', 'adjustment'], name='inventory_s_organiz_37a711_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustmentitem',
            index=models.Index(fields=['organization', 'product'], name='inventory_s_organiz_0e19ed_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferitem',
            index=models.Index(fields=['organization', 'transfer'], name='inventory_s_organiz_26303a_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferitem',
            index=models.Index(fields=['organization', 'product'], name='inventory_s_organiz_ba2221_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['organization', 'code'], name='inventory_u_organiz_425719_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['organization', 'is_active'], name='inventory_u_organiz_86500c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'code'], name='inventory_p_organiz_765c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'is_active'], name='inventory_p_organiz_f121a4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'category'], name='inventory_p_organiz_843cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'brand'], name='inventory_p_organiz_d334f5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'barcode'], name='inventory_p_organiz_f7f8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='inventory_p_product_3c97c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['organization', 'code'], name='inventory_w_organiz_571767_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['organization', 'is_active'], name='inventory_w_organiz_c92182_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['organization', 'transfer_number'], name='inventory_s_organiz_578b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['organization', 'status'], name='inventory_s_organiz_78e9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['organization', 'source_warehouse'], name='inventory_s_organiz_0c6a93_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['organization', 'destination_warehouse'], name='inventory_s_organiz_dcc0b7_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['-transfer_date'], name='inventory_s_transfe_8bf640_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktransfer',
            unique_together={('organization', 'transfer_number')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'product'], name='inventory_s_organiz_b34d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'warehouse'], name='inventory_s_organiz_de598b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'movement_type'], name='inventory_s_organiz_1dc4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'movement_date'], name='inventory_s_organiz_8c6956_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-movement_date'], name='inventory_s_movemen_8532d9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['organization', 'adjustment_number'], name='inventory_s_organiz_f29c86_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['organization', 'status'], name='inventory_s_organiz_df0457_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['organization', 'warehouse'], name='inventory_s_organiz_a24b98_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['-adjustment_date'], name='inventory_s_adjustm_0dfb39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockadjustment',
            unique_together={('organization', 'adjustment_number')},
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['organization', 'product'], name='inventory_p_organiz_c01853_idx'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['organization', 'warehouse'], name='inventory_p_organiz_ebcade_idx'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['organization', 'product', 'warehouse'], name='inventory_p_organiz_c253c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('organization', 'product', 'warehouse')},
        ),
    ]
