# Generated by Django 5.2.4 on 2026-05-18 10:34

from django.db import migrations


def create_inventory_permissions(apps, schema_editor):
    """Create all inventory module permissions."""
    Permission = apps.get_model('core', 'Permission')
    
    # Define all inventory permissions (34 total)
    INVENTORY_PERMISSIONS = [
        # Category (4)
        ('inventory.category.create', 'Create product categories'),
        ('inventory.category.read', 'View product categories'),
        ('inventory.category.update', 'Update product categories'),
        ('inventory.category.delete', 'Delete product categories'),
        
        # Brand (4)
        ('inventory.brand.create', 'Create brands'),
        ('inventory.brand.read', 'View brands'),
        ('inventory.brand.update', 'Update brands'),
        ('inventory.brand.delete', 'Delete brands'),
        
        # Unit (4)
        ('inventory.unit.create', 'Create units of measurement'),
        ('inventory.unit.read', 'View units of measurement'),
        ('inventory.unit.update', 'Update units of measurement'),
        ('inventory.unit.delete', 'Delete units of measurement'),
        
        # Warehouse (4)
        ('inventory.warehouse.create', 'Create warehouses'),
        ('inventory.warehouse.read', 'View warehouses'),
        ('inventory.warehouse.update', 'Update warehouses'),
        ('inventory.warehouse.delete', 'Delete warehouses'),
        
        # Product (5)
        ('inventory.product.create', 'Create products'),
        ('inventory.product.read', 'View products'),
        ('inventory.product.update', 'Update products'),
        ('inventory.product.delete', 'Delete products'),
        ('inventory.product.view_stock', 'View product stock levels'),
        
        # Stock (2)
        ('inventory.stock.read', 'View stock levels'),
        ('inventory.stock.view_movements', 'View stock movement history'),
        
        # Transfer (5)
        ('inventory.transfer.create', 'Create stock transfers'),
        ('inventory.transfer.read', 'View stock transfers'),
        ('inventory.transfer.update', 'Update stock transfers'),
        ('inventory.transfer.delete', 'Delete stock transfers'),
        ('inventory.transfer.complete', 'Complete/execute stock transfers'),
        
        # Adjustment (6)
        ('inventory.adjustment.create', 'Create stock adjustments'),
        ('inventory.adjustment.read', 'View stock adjustments'),
        ('inventory.adjustment.update', 'Update stock adjustments'),
        ('inventory.adjustment.delete', 'Delete stock adjustments'),
        ('inventory.adjustment.approve', 'Approve stock adjustments'),
        ('inventory.adjustment.reject', 'Reject stock adjustments'),
    ]
    
    # Create permissions
    for code, description in INVENTORY_PERMISSIONS:
        Permission.objects.get_or_create(
            permission_code=code,
            defaults={'description': description}
        )


def remove_inventory_permissions(apps, schema_editor):
    """Remove inventory permissions on migration reversal."""
    Permission = apps.get_model('core', 'Permission')
    Permission.objects.filter(permission_code__startswith='inventory.').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('core', '0004_rbac_data_setup'),  # Ensure Permission model exists
    ]

    operations = [
        migrations.RunPython(
            create_inventory_permissions,
            remove_inventory_permissions
        ),
    ]
