# Generated by Django on 2026-05-21 07:11

from django.db import migrations


def add_update_permissions(apps, schema_editor):
    """Add missing update permissions for transfers and adjustments."""
    Permission = apps.get_model('core', 'Permission')
    
    permissions = [
        ('inventory.update_transfers', 'Update Stock Transfers', 'Can update stock transfer records'),
        ('inventory.update_adjustments', 'Update Stock Adjustments', 'Can update stock adjustment records'),
    ]
    
    for code, name, description in permissions:
        Permission.objects.get_or_create(
            permission_code=code,
            defaults={'name': name, 'description': description}
        )


def remove_update_permissions(apps, schema_editor):
    """Remove update permissions on migration reversal."""
    Permission = apps.get_model('core', 'Permission')
    Permission.objects.filter(
        permission_code__in=[
            'inventory.update_transfers',
            'inventory.update_adjustments',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_permissions'),
        ('core', '0004_rbac_data_setup'),  # Ensure Permission model exists
    ]

    operations = [
        migrations.RunPython(
            add_update_permissions,
            remove_update_permissions
        ),
    ]
