# Generated by Django 5.2.4 on 2026-05-05 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Department name (e.g., Human Resources, Information Technology)', max_length=100)),
                ('code', models.CharField(help_text='Unique department code within organization (e.g., HR, IT, FIN)', max_length=20)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the department's purpose and responsibilities")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is currently active')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Designation name (e.g., Senior Manager, Software Engineer)', max_length=100)),
                ('code', models.CharField(help_text='Unique designation code within organization (e.g., MGR, SE, ACC)', max_length=20)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the designation's role and responsibilities")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this designation is currently active')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(help_text='Unique employee code within organization', max_length=20)),
                ('first_name', models.CharField(help_text="Employee's first name", max_length=100)),
                ('middle_name', models.CharField(blank=True, help_text="Employee's middle name (optional)", max_length=100)),
                ('last_name', models.CharField(help_text="Employee's last name", max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text="Employee's date of birth", null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], help_text="Employee's gender", max_length=10)),
                ('joining_date', models.DateField(help_text='Date when employee joined the organization')),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TERMINATED', 'Terminated'), ('RESIGNED', 'Resigned')], default='ACTIVE', help_text='Current employment status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the employee is currently active')),
                ('department', models.ForeignKey(blank=True, help_text='Department where the employee works', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.department')),
                ('designation', models.ForeignKey(blank=True, help_text='Job title or position of the employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.designation')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('user', models.OneToOneField(blank=True, help_text='Link to user account for login-enabled employees', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_email', models.EmailField(blank=True, help_text='Personal email address', max_length=254)),
                ('official_email', models.EmailField(blank=True, help_text='Official/company email address', max_length=254)),
                ('mobile_number', models.CharField(help_text='Primary mobile/phone number', max_length=20)),
                ('alternate_mobile', models.CharField(blank=True, help_text='Alternate contact number', max_length=20)),
                ('present_address', models.TextField(blank=True, help_text='Current residential address')),
                ('permanent_address', models.TextField(blank=True, help_text='Permanent/home address')),
                ('city', models.CharField(blank=True, help_text='City of residence', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/province of residence', max_length=100)),
                ('country', models.CharField(blank=True, help_text='Country of residence', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20)),
                ('employee', models.OneToOneField(help_text='Employee this contact information belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='hrm.employee')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Employee Contact Information',
                'verbose_name_plural': 'Employee Contact Information',
            },
        ),
        migrations.CreateModel(
            name='EmployeeGovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_id', models.CharField(blank=True, help_text='National ID number (CNIC/NIC)', max_length=50)),
                ('passport_number', models.CharField(blank=True, help_text='Passport number', max_length=50)),
                ('tax_identification', models.CharField(blank=True, help_text='Tax identification number (NTN)', max_length=50)),
                ('social_security', models.CharField(blank=True, help_text='Social security number (EOBI)', max_length=50)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number for salary deposits', max_length=50)),
                ('bank_name', models.CharField(blank=True, help_text='Name of the bank', max_length=100)),
                ('bank_branch', models.CharField(blank=True, help_text='Bank branch location', max_length=100)),
                ('employee', models.OneToOneField(help_text='Employee this government information belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='government_info', to='hrm.employee')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Employee Government Information',
                'verbose_name_plural': 'Employee Government Information',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Employee type name (e.g., Permanent, Contract, Probation, Intern)', max_length=100)),
                ('code', models.CharField(help_text='Unique employee type code within organization (e.g., PERM, CONT, PROB)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the employee type and its terms')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this employee type is currently active')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Employee Type',
                'verbose_name_plural': 'Employee Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(blank=True, help_text='Employment type (Permanent, Contract, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.employeetype'),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Qualification name (e.g., Bachelor's Degree, Master's Degree, PhD)", max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique qualification code (e.g., BS, MS, PHD, DIPLOMA)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the qualification level and requirements')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this qualification is currently active')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='hrm_qualifi_code_efa230_idx'), models.Index(fields=['is_active'], name='hrm_qualifi_is_acti_fbe73e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Religion name (e.g., Islam, Christianity, Hinduism, Buddhism)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the religion')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this religion option is currently active')),
            ],
            options={
                'verbose_name': 'Religion',
                'verbose_name_plural': 'Religions',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='hrm_religio_name_38bb63_idx'), models.Index(fields=['is_active'], name='hrm_religio_is_acti_85d9ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeePersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father_name', models.CharField(blank=True, help_text="Father's full name", max_length=100)),
                ('mother_name', models.CharField(blank=True, help_text="Mother's full name", max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], help_text='Current marital status', max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Blood group type', max_length=5)),
                ('nationality', models.CharField(blank=True, help_text='Nationality/citizenship', max_length=50)),
                ('employee', models.OneToOneField(help_text='Employee this personal information belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='hrm.employee')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('qualification', models.ForeignKey(blank=True, help_text='Highest educational qualification from global master data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.qualification')),
                ('religion', models.ForeignKey(blank=True, help_text='Religious affiliation from global master data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.religion')),
            ],
            options={
                'verbose_name': 'Employee Personal Information',
                'verbose_name_plural': 'Employee Personal Information',
            },
        ),
        migrations.CreateModel(
            name='ScaleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Scale category name (e.g., Scale A, Executive Scale, Officer Grade)', max_length=100)),
                ('code', models.CharField(help_text='Unique scale category code within organization (e.g., SA, SB, ES)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the scale category and salary range')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scale category is currently active')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Scale Category',
                'verbose_name_plural': 'Scale Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='scale_category',
            field=models.ForeignKey(blank=True, help_text='Salary scale or grade category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.scalecategory'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Shift name (e.g., Morning Shift, Night Shift, General)', max_length=100)),
                ('code', models.CharField(help_text='Unique shift code within organization (e.g., MS, NS, GS)', max_length=20)),
                ('start_time', models.TimeField(help_text='Shift start time (e.g., 08:00:00)')),
                ('end_time', models.TimeField(help_text='Shift end time (e.g., 17:00:00)')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the shift timing and requirements')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this shift is currently active')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Working shift assigned to the employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.shift'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization', 'code'], name='hrm_departm_organiz_544c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization', 'is_active'], name='hrm_departm_organiz_579363_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['organization', 'code'], name='hrm_designa_organiz_4e26af_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['organization', 'is_active'], name='hrm_designa_organiz_dc3548_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='employeecontact',
            index=models.Index(fields=['organization', 'employee'], name='hrm_employe_organiz_e583a3_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecontact',
            index=models.Index(fields=['organization', 'mobile_number'], name='hrm_employe_organiz_eb93de_idx'),
        ),
        migrations.AddIndex(
            model_name='employeegovernment',
            index=models.Index(fields=['organization', 'employee'], name='hrm_employe_organiz_7f470f_idx'),
        ),
        migrations.AddIndex(
            model_name='employeegovernment',
            index=models.Index(fields=['organization', 'national_id'], name='hrm_employe_organiz_21ed39_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetype',
            index=models.Index(fields=['organization', 'code'], name='hrm_employe_organiz_c14490_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetype',
            index=models.Index(fields=['organization', 'is_active'], name='hrm_employe_organiz_9b970e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeetype',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='employeepersonal',
            index=models.Index(fields=['organization', 'employee'], name='hrm_employe_organiz_b206eb_idx'),
        ),
        migrations.AddIndex(
            model_name='scalecategory',
            index=models.Index(fields=['organization', 'code'], name='hrm_scaleca_organiz_96dc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='scalecategory',
            index=models.Index(fields=['organization', 'is_active'], name='hrm_scaleca_organiz_3d0d1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scalecategory',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['organization', 'code'], name='hrm_shift_organiz_eaf49e_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['organization', 'is_active'], name='hrm_shift_organiz_337c76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'employee_code'], name='hrm_employe_organiz_bad275_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'employment_status'], name='hrm_employe_organiz_20226e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('organization', 'employee_code')},
        ),
    ]
